<?php 
$title = 'My Movies';
 $this->headTitle($title);
 ?> 
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <!--<p>
     <a href="<?php //echo $this->url('movie', array('action'=>'add'));?>">Add new movie</a>
 </p> -->

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Year</th>
     <th>&nbsp;</th>
 </tr>
 <?php   
   $form->setAttribute('action', $this->url('account', array('action' => 'edit', 'id' => $account_id)));     
   $form->prepare();
   echo $this->form()->openTag($form);
   $i = 1;     
 ?>
 
 
 <?php foreach ($movies as $movie) : ?>
 
 <tr> 
     <td><?php echo $this->escapeHtml($movie->title);?></td>
     <td><?php echo $this->escapeHtml($movie->year);?></td>    
     <td><?php echo $this->formRow($form->get('selected_'.$i));
      echo $this->formRow($form->get('movie_id_'.$i)->setValue($movie->id));  
     
      ?></td>  
     <!--<td>
         <a href="<?php //cho $this->url('movie',
             //array('action'=>'edit', 'id' => $movie->id));?>">Edit</a>
         <a href="<?php //echo $this->url('movie',
             //array('action'=>'delete', 'id' => $movie->id));?>">Delete</a>
     </td> -->
 </tr>
 <?php $i++; 
  endforeach; ?>  
 </table>
 
 <?php   
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 
 
 ?> 