<?php
 // module/Account/view/account/account/delete.phtml:

 $title = 'Delete account';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete
     '<?php echo $this->escapeHtml($account->first_name); ?>' by
     '<?php echo $this->escapeHtml($account->last_name); ?>'?
 </p>
 <?php
 $url = $this->url('account', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $account->id; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>