<?php
 // module/Movie/view/movie/movie/add.phtml:

 $title = 'Add new movie';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('movie', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id')); 
 echo $this->formRow($form->get('year')) . "</br>";
 echo $this->formRow($form->get('title'));
 echo $this->formSubmit($form->get('submit'));
 //echo $this->formCollection($form);
 echo $this->form()->closeTag();