<?php 
$title = 'Select movies';
 $this->headTitle($title);
 ?> 
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <!--<p>
     <a href="<?php //echo $this->url('movie', array('action'=>'add'));?>">Add new movie</a>
 </p> -->

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Year</th>
     <th>Price</th>
 </tr>
 <?php   
   $form->setAttribute('action', $this->url('account', array('action' => 'edit', 'id' => $account_id)));     
   $form->prepare();
   echo $this->form()->openTag($form);
   $i = 1;     
 ?>
 
 
 <?php foreach ($movies as $movie) : ?>
 
 <tr> 
     <td><?php echo $this->escapeHtml($movie->title);?></td>
     <td><?php echo $this->escapeHtml($movie->year);?></td>  
     <td><?php echo $this->escapeHtml('$'.number_format($movie->price,2,'.',','));?></td>
     <td><?php echo $this->formRow($form->get('selected_'.$i));
      echo $this->formRow($form->get('movie_id_'.$i)->setValue($movie->id)); 
      echo $this->formRow($form->get('price_'.$i)->setValue($movie->price));     
      ?></td>  
    
 </tr>
 <?php $i++; 
  endforeach; ?>  
 </table>
 
 <?php   
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 
 
 ?> 