<?php
 // module/Account/view/account/account/edit.phtml:

 $title = 'Edit account';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'account',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('id'));
  echo $this->formRow($form->get('first_name')) . "</br>";
 // echo $this->formRow($form->get('middle_initial'));
 echo $this->formRow($form->get('last_name'));
 echo $this->formRow($form->get('street'));
 echo $this->formRow($form->get('apt_no'));   
 echo $this->formRow($form->get('city'));  
 echo $this->formRow($form->get('state'));     
 echo $this->formRow($form->get('zip')); 
 echo $this->formRow($form->get('movie_id_1'));   
 echo $this->formRow($form->get('movie_id_2'));                   
 echo $this->formRow($form->get('movie_id_3'));                                   
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();